---
openapi: 3.0.0
info:
  title: Example
  version: '1'
  description: ''
servers:
- url: https://example.com
paths:
  "/example":
    get:
      operationId: Example
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LiveRateCreateRequest'
      responses:
        '200':
          description: example
  "/example-two":
    get:
      operationId: ExampleTwo
      responses:
        '200':
          $ref: '#/components/responses/exampleTwoResponse'
components:
  responses:
    exampleTwoResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Shipment'
  schemas:
    LiveRateCreateRequest:
      type: object
      description: The rate request
      properties:
        address_from:
          oneOf:
            - type: string
              description: |-
                Object ID for an existing <a href="#tag/Addresses">Address</a>
            - $ref: '#/components/schemas/AddressComplete'
    Shipment:
      type: object
      description: The shipment
      properties:
        address_from:
          $ref: '#/components/schemas/AddressFrom'
    AddressFrom:
      type: object
      description: |-
        <a href="#tag/Addresses">Address</a> object of the sender / seller. Will be returned expanded by default.
      allOf:
        - $ref: '#/components/schemas/Address'
    Address:
      type: object
      description: The address
      properties:
        city:
          description: |-
            Name of a city.
          example: 'San Francisco'
          type: string
    AddressComplete:
      type: object
      description: The complete address
      properties:
        state:
          description: |-
            Name of a state.
          type: string
