---
openapi: 3.0.0
info:
  title: Example
  version: '1'
  description: ''
servers:
- url: https://example.com
paths:
  "/example":
    get:
      operationId: Example
      parameters:
        - $ref: "#/components/parameters/HeaderParam"
      responses:
        '200':
          description: example
components:
  parameters:
    HeaderParam:
      description: The number of results to return per page (max 100)
      in: header
      name: header_param
      schema:
        type: string
  responses: {}
