---
openapi: 3.0.0
info:
  title: Example
  version: '1'
  description: ''
servers:
- url: https://example.com
paths:
  "/example":
    post:
      operationId: Example
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressValidationResultsMessage'
      responses:
        '200':
          description: example
components:
  responses: {}
  schemas:
    AddressValidationResultsMessage:
      properties:
        code:
          enum:
            - unknown_street
            - Unknown Street
          example: 'Unknown Street'
          type: string
      type: object
