---
openapi: 3.0.0
info:
  title: Example
  version: '1'
  description: ''
servers:
- url: https://example.com
paths:
  "/example":
    get:
      operationId: Example
      parameters:
        - $ref: "#/components/parameters/ResultsPerPageQueryParam"
      responses:
        '200':
          description: example
components:
  parameters:
    ResultsPerPageQueryParam:
      description: The number of results to return per page (max 100)
      in: query
      name: results_per_page
      schema:
        type: integer
        format: int64
        maximum: 100
        default: 25
  responses: {}
