---
openapi: 3.0.0
info:
  title: Example
  version: '1'
  description: ''
servers:
- url: https://example.com
paths:
  "/example":
    post:
      operationId: Example
      parameters:
        - $ref: "#/components/parameters/HeaderParam"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
      responses:
        '201':
          $ref: '#/components/responses/multiResponse'
components:
  parameters:
    HeaderParam:
      description: The number of results to return per page (max 100)
      in: header
      name: header_param
      schema:
        type: string
  responses:
    multiResponse:
      description: ''
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ExampleOneResponse'
              - $ref: '#/components/schemas/ExampleTwoResponse'
  schemas:
    ExampleBody:
      type: object
      properties:
        example:
          type: string
    ExampleOneResponse:
      type: object
      properties:
        field:
          type: string
    ExampleTwoResponse:
      type: object
      properties:
        field:
          $ref: '#/components/schemas/ExampleBody'
